 /******************************************************************************
 *
 * Module: ULTRASONIC
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the AVR ULTRASONIC driver
 *
 * Author: Mohamed Khaled
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>

/*******************************************************************************
 *                      Private Global Variable                                *
 *******************************************************************************/

/* Global Variable to store edge counts */
static volatile uint8 g_edgeCount = 0;

/* Global Variable to store periodic time */
static volatile uint16 g_timePeriod = 0;

/* Global Variable to store high time plus period */
static volatile uint16 g_timePeriodPlusHigh = 0;

/*******************************************************************************
 *                      Private Functions Prototypes                           *
 *******************************************************************************/

/*
 * Description :
 * Send the Trigger pulse to the Ultrasonic
 * (Transmit at least 10 us trigger pulse to the Ultrasonic)
 */
static void Ultrasonic_Trigger(void);

/*
 * Description :
 * 1. This is the call back function called by the ICU driver
 * 2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
static void Ultrasonic_edgeProcessing(void);

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Initialize Ultrasonic sensor:
 * 1. Initialize the ICU driver
 * 2. Setup the ICU call back function
 * 3. Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void){

	/* Set Callback Function */
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	/* Configure ICU settings */
	Icu_ConfigType config = {RISING_EDGE,F_CPU_8};

	/* Initiate ICU */
	ICU_init(&config);

	/* Set trigger pin as output pin */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
}

/*
 * Description :
 * Send the Trigger pulse to the Ultrasonic
 * (Transmit at least 10 us trigger pulse to the Ultrasonic)
 */
static void Ultrasonic_Trigger(void){

	/* Set trigger pin High */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);

	/* wait 10 us */
	_delay_us(10);

	/* Set trigger pin Low */
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function
 * 2. Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance(void){

	/* Store Value of distance */
	static uint16 distance = 0;

	/* Send the trigger pulse */
	Ultrasonic_Trigger();

	/* Wait for edges */
	while(g_edgeCount < 2);

	if((g_edgeCount > 2) && (g_edgeCount < 4)){

		/* wait for edges */
		while(g_edgeCount < 4);
	}

	if(g_edgeCount == 4){

		/* Reset edge counter */
		g_edgeCount = 0;

		/* Store the value of high time */
		distance = (((uint16)g_timePeriodPlusHigh - g_timePeriod)/ULTRASONIC_CALIBRATION_FACTOR);
	}

	return distance;
}

/*
 * Description :
 * 1. This is the call back function called by the ICU driver
 * 2. This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
static void Ultrasonic_edgeProcessing(void){

	/* Increment edge counter */
	g_edgeCount++;

	if(g_edgeCount == 1){

		/* Clear TIMER1 counter to count only the high time*/
		ICU_clearTimerValue();

		/* Change the edge to falling from rising */
		ICU_setEdgeDetectionType(FALLING_EDGE);
	}
	else if(g_edgeCount == 2){

		/* Return it to rising edge again */
		ICU_setEdgeDetectionType(RISING_EDGE);
	}
	else if(g_edgeCount == 3){

		/* Get period time value from TIMER1 counter */
		g_timePeriod = ICU_getInputCaptureValue();

		/* Return it to falling edge again */
		ICU_setEdgeDetectionType(FALLING_EDGE);
	}
	else if(g_edgeCount == 4){

		/* Get high time plus period value from TIMER1 counter */
		g_timePeriodPlusHigh = ICU_getInputCaptureValue();

		/* Return it to rising edge again */
		ICU_setEdgeDetectionType(RISING_EDGE);
	}
}
